# Generated by Django 3.2.6 on 2021-08-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_account',
            field=models.BooleanField(default=False),
        ),
    ]
